//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.12 at 06:57:05 PM CET 
//


package com.avtest.soap_web_servicecf;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.avtest.soap_web_servicecf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WorkoutRequest_QNAME = new QName("http://avtest.com/soap-web-serviceCF", "WorkoutRequest");
    private final static QName _WorkoutResponse_QNAME = new QName("http://avtest.com/soap-web-serviceCF", "WorkoutResponse");
    private final static QName _Workouts_QNAME = new QName("http://avtest.com/soap-web-serviceCF", "Workouts");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.avtest.soap_web_servicecf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WorkoutRequestType }
     * 
     */
    public WorkoutRequestType createWorkoutRequestType() {
        return new WorkoutRequestType();
    }

    /**
     * Create an instance of {@link WorkoutResponseType }
     * 
     */
    public WorkoutResponseType createWorkoutResponseType() {
        return new WorkoutResponseType();
    }

    /**
     * Create an instance of {@link WorkoutsWrapperType }
     * 
     */
    public WorkoutsWrapperType createWorkoutsWrapperType() {
        return new WorkoutsWrapperType();
    }

    /**
     * Create an instance of {@link XMLWorkoutResponseType }
     * 
     */
    public XMLWorkoutResponseType createXMLWorkoutResponseType() {
        return new XMLWorkoutResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkoutRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WorkoutRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://avtest.com/soap-web-serviceCF", name = "WorkoutRequest")
    public JAXBElement<WorkoutRequestType> createWorkoutRequest(WorkoutRequestType value) {
        return new JAXBElement<WorkoutRequestType>(_WorkoutRequest_QNAME, WorkoutRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkoutResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WorkoutResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://avtest.com/soap-web-serviceCF", name = "WorkoutResponse")
    public JAXBElement<WorkoutResponseType> createWorkoutResponse(WorkoutResponseType value) {
        return new JAXBElement<WorkoutResponseType>(_WorkoutResponse_QNAME, WorkoutResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkoutsWrapperType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WorkoutsWrapperType }{@code >}
     */
    @XmlElementDecl(namespace = "http://avtest.com/soap-web-serviceCF", name = "Workouts")
    public JAXBElement<WorkoutsWrapperType> createWorkouts(WorkoutsWrapperType value) {
        return new JAXBElement<WorkoutsWrapperType>(_Workouts_QNAME, WorkoutsWrapperType.class, null, value);
    }

}
