//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.12 at 06:57:05 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://avtest.com/soap-web-serviceCF", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.avtest.soap_web_servicecf;
