//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.12 at 06:57:05 PM CET 
//


package com.avtest.soap_web_servicecf;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkoutType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="WorkoutType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CHEST"/&gt;
 *     &lt;enumeration value="LEGS"/&gt;
 *     &lt;enumeration value="BACK"/&gt;
 *     &lt;enumeration value="TRICEPS"/&gt;
 *     &lt;enumeration value="BICEPS"/&gt;
 *     &lt;enumeration value="NECK"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "WorkoutType")
@XmlEnum
public enum WorkoutType {

    CHEST,
    LEGS,
    BACK,
    TRICEPS,
    BICEPS,
    NECK;

    public String value() {
        return name();
    }

    public static WorkoutType fromValue(String v) {
        return valueOf(v);
    }

}
