//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.12 at 06:57:05 PM CET 
//


package com.avtest.soap_web_servicecf;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.xml.bind.annotation.*;
import lombok.Getter;
import lombok.Setter;

import java.util.Map;


/**
 * <p>Java class for XMLWorkoutResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XMLWorkoutResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="workoutId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Instructions" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NumberOfSets" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="SetDuration" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ImageContent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "Workout")
@XmlAccessorType(XmlAccessType.FIELD)
@Getter
@Setter
public class XMLWorkoutResponseType {

    @XmlElement(name = "workoutId")
    @JsonProperty("workoutId")
    private Long workoutId;

    @XmlElement(name = "Name")
    private String name;

    @XmlElement(name = "Instructions")
    private String instructions;

    @XmlElement(name = "Type")
    private String type;

    @XmlElement(name = "NumberOfSets")
    private Integer numberOfSets;

    @XmlElement(name = "SetDuration")
    private Integer setDuration;

    @XmlElement(name = "ImageContent")
    private String imageContent;

    @JsonProperty("image")
    private void unpackNestedImageContent(Map<String, Object> image) {
        this.imageContent = (String) image.get("content");
    }

    /**
     * Gets the value of the workoutId property.
     * 
     */
    public long getWorkoutId() {
        return workoutId;
    }

    /**
     * Sets the value of the workoutId property.
     * 
     */
    public void setWorkoutId(long value) {
        this.workoutId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the instructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstructions() {
        return instructions;
    }

    /**
     * Sets the value of the instructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstructions(String value) {
        this.instructions = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the numberOfSets property.
     * 
     */
    public int getNumberOfSets() {
        return numberOfSets;
    }

    /**
     * Sets the value of the numberOfSets property.
     * 
     */
    public void setNumberOfSets(int value) {
        this.numberOfSets = value;
    }

    /**
     * Gets the value of the setDuration property.
     * 
     */
    public int getSetDuration() {
        return setDuration;
    }

    /**
     * Sets the value of the setDuration property.
     * 
     */
    public void setSetDuration(int value) {
        this.setDuration = value;
    }

    /**
     * Gets the value of the imageContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageContent() {
        return imageContent;
    }

    /**
     * Sets the value of the imageContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageContent(String value) {
        this.imageContent = value;
    }

}
